name: fractional_indexing_dart
description: A Dart implementation of fractional indexing for efficient list ordering and reordering without large-scale updates. Ideal for CRDTs and real-time apps.
version: 1.0.0
homepage: https://github.com/bthnkucuk/fractional_indexing_dart
repository: https://github.com/bthnkucuk/fractional_indexing_dart
issue_tracker: https://github.com/bthnkucuk/fractional_indexing_dart/issues

topics:
  - algorithms
  - sorting
  - crdt
  - indexing
  - list-ordering

environment:
  sdk: ^3.10.3

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
