name: fractional_indexing_dart
description: A Dart implementation of fractional indexing for efficient list ordering and reordering without large-scale updates. Ideal for CRDTs and real-time apps.
version: 1.0.4
homepage: https://github.com/bthnkucuk/fractional-indexing-dart
repository: https://github.com/bthnkucuk/fractional-indexing-dart
issue_tracker: https://github.com/bthnkucuk/fractional-indexing-dart/issues

topics:
  - algorithms
  - sorting
  - crdt
  - indexing
  - list-ordering

environment:
  sdk: ">=3.6.0 <4.0.0"
# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
